version: 2
updates:
 - package-ecosystem: "npm" # See documentation for possible values
   directory: "/" # Location of package manifests
   schedule:
     interval: "weekly"
   target-branch: "dev"
   open-pull-requests-limit: 10